export const deviceSpecs = [
  {
    id: "ds1",
    listingId: "l1",
    ram: 8,
    storage: 256,
    year: 2018,
    os: "WINDOWS",
    screenSize: 14.0,
    processor: "Intel Core i5-8350U",
    color: "Black",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: true,
    hasCharger: true,
    notes: null,
  },
  {
    id: "ds2",
    listingId: "l2",
    ram: 3,
    storage: 32,
    year: 2020,
    os: "ANDROID",
    screenSize: 10.4,
    processor: "Qualcomm Snapdragon 662",
    color: "Grey",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: false,
    hasCharger: true,
    notes: null,
  },
  {
    id: "ds3",
    listingId: "l3",
    ram: 4,
    storage: 64,
    year: 2019,
    os: "IOS",
    screenSize: 6.1,
    processor: "Apple A13 Bionic",
    color: "White",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: false,
    hasCharger: false,
    notes: "Charger not included",
  },
  {
    id: "ds4",
    listingId: "l4",
    ram: 16,
    storage: 512,
    year: 2019,
    os: "WINDOWS",
    screenSize: 14.0,
    processor: "Intel Core i7-8550U",
    color: "Silver",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: true,
    hasCharger: true,
    notes: null,
  },
  {
    id: "ds5",
    listingId: "l5",
    ram: 8,
    storage: 256,
    year: 2017,
    os: "LINUX",
    screenSize: 14.0,
    processor: "Intel Core i5-7200U",
    color: "Black",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: true,
    hasCharger: true,
    notes: "Ubuntu 22.04 installed",
  },
  {
    id: "ds6",
    listingId: "l6",
    ram: 3,
    storage: 32,
    year: 2020,
    os: "IOS",
    screenSize: 10.2,
    processor: "Apple A12 Bionic",
    color: "Space Grey",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: false,
    hasCharger: true,
    notes: null,
  },
  {
    id: "ds7",
    listingId: "l7",
    ram: 6,
    storage: 128,
    year: 2021,
    os: "ANDROID",
    screenSize: 6.5,
    processor: "Qualcomm Snapdragon 720G",
    color: "Awesome Black",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: false,
    hasCharger: true,
    notes: null,
  },
  {
    id: "ds8",
    listingId: "l8",
    ram: 8,
    storage: 256,
    year: 2019,
    os: "MACOS",
    screenSize: 13.3,
    processor: "Intel Core i5-8210Y",
    color: "Gold",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: true,
    hasCharger: true,
    notes: null,
  },
  {
    id: "ds9",
    listingId: "l9",
    ram: 4,
    storage: 64,
    year: 2022,
    os: "ANDROID",
    screenSize: 6.6,
    processor: "Helio G85",
    color: "Atlantic Blue",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: false,
    hasCharger: true,
    notes: null,
  },
  {
    id: "ds10",
    listingId: "l10",
    ram: 4,
    storage: 64,
    year: 2020,
    os: "CHROMEOS",
    screenSize: 14.0,
    processor: "Intel Celeron N4020",
    color: "Silver",
    hasCamera: true,
    hasMicrophone: true,
    hasKeyboard: true,
    hasCharger: true,
    notes: null,
  },
];
