export const listings = [
  {
    id: "l1",
    donorId: "u1",
    deviceType: "LAPTOP",
    title: "Dell Latitude 5490",
    brand: "Dell",
    model: "Latitude 5490",
    condition: "GOOD",
    photos: [],
    countryCode: "GH",
    status: "ACTIVE",
    expiresAt: "2026-09-01",
    specId: "ds1",
  },
  {
    id: "l2",
    donorId: "u3",
    deviceType: "TABLET",
    title: "Samsung Galaxy Tab A7",
    brand: "Samsung",
    model: "Galaxy Tab A7",
    condition: "FAIR",
    photos: [],
    countryCode: "GH",
    status: "ACTIVE",
    expiresAt: "2026-08-15",
    specId: "ds2",
  },
  {
    id: "l3",
    donorId: "u6",
    deviceType: "SMARTPHONE",
    title: "iPhone 11",
    brand: "Apple",
    model: "iPhone 11",
    condition: "GOOD",
    photos: [],
    countryCode: "GH",
    status: "MATCHED",
    expiresAt: "2026-07-30",
    specId: "ds3",
  },
  {
    id: "l4",
    donorId: "u8",
    deviceType: "LAPTOP",
    title: "HP EliteBook 840 G5",
    brand: "HP",
    model: "EliteBook 840 G5",
    condition: "GOOD",
    photos: [],
    countryCode: "NG",
    status: "ACTIVE",
    expiresAt: "2026-09-10",
    specId: "ds4",
  },
  {
    id: "l5",
    donorId: "u9",
    deviceType: "LAPTOP",
    title: "Lenovo ThinkPad T470",
    brand: "Lenovo",
    model: "ThinkPad T470",
    condition: "FAIR",
    photos: [],
    countryCode: "GH",
    status: "ACTIVE",
    expiresAt: "2026-08-20",
    specId: "ds5",
  },
  {
    id: "l6",
    donorId: "u1",
    deviceType: "TABLET",
    title: "iPad 8th Generation",
    brand: "Apple",
    model: "iPad 8th Gen",
    condition: "LIKE_NEW",
    photos: [],
    countryCode: "GH",
    status: "ACTIVE",
    expiresAt: "2026-09-05",
    specId: "ds6",
  },
  {
    id: "l7",
    donorId: "u3",
    deviceType: "SMARTPHONE",
    title: "Samsung Galaxy A52",
    brand: "Samsung",
    model: "Galaxy A52",
    condition: "FAIR",
    photos: [],
    countryCode: "GH",
    status: "ACTIVE",
    expiresAt: "2026-08-01",
    specId: "ds7",
  },
  {
    id: "l8",
    donorId: "u5",
    deviceType: "LAPTOP",
    title: "MacBook Air 2019",
    brand: "Apple",
    model: "MacBook Air",
    condition: "GOOD",
    photos: [],
    countryCode: "NG",
    status: "CLOSED",
    expiresAt: "2026-06-01",
    specId: "ds8",
  },
  {
    id: "l9",
    donorId: "u8",
    deviceType: "SMARTPHONE",
    title: "Tecno Spark 8",
    brand: "Tecno",
    model: "Spark 8",
    condition: "FAIR",
    photos: [],
    countryCode: "NG",
    status: "ACTIVE",
    expiresAt: "2026-08-25",
    specId: "ds9",
  },
  {
    id: "l10",
    donorId: "u6",
    deviceType: "LAPTOP",
    title: "Acer Chromebook 14",
    brand: "Acer",
    model: "Chromebook 14",
    condition: "GOOD",
    photos: [],
    countryCode: "GH",
    status: "ACTIVE",
    expiresAt: "2026-09-15",
    specId: "ds10",
  },
];
