export const offers = [
  {
    id: "o1",
    listingId: "l3",
    requestId: "r3",
    status: "ACCEPTED",
    message: "I think this is a great match, let's connect.",
  },
  {
    id: "o2",
    listingId: "l1",
    requestId: "r1",
    status: "PENDING",
    message: null,
  },
  {
    id: "o3",
    listingId: "l4",
    requestId: "r4",
    status: "PENDING",
    message: "This EliteBook should handle your design work well.",
  },
  {
    id: "o4",
    listingId: "l2",
    requestId: "r2",
    status: "DECLINED",
    message: null,
  },
  {
    id: "o5",
    listingId: "l5",
    requestId: "r6",
    status: "PENDING",
    message: "Linux already installed, should be perfect for coding.",
  },
  {
    id: "o6",
    listingId: "l7",
    requestId: "r5",
    status: "PENDING",
    message: null,
  },
  {
    id: "o7",
    listingId: "l9",
    requestId: "r9",
    status: "PENDING",
    message: "Still works great for calls and browsing.",
  },
  {
    id: "o8",
    listingId: "l6",
    requestId: "r7",
    status: "ACCEPTED",
    message: "Easy to use for older folks, happy to help.",
  },
  {
    id: "o9",
    listingId: "l10",
    requestId: "r10",
    status: "PENDING",
    message: null,
  },
  {
    id: "o10",
    listingId: "l8",
    requestId: "r8",
    status: "DECLINED",
    message: "Already found a closer match.",
  },
];
