export const requests = [
  {
    id: "r1",
    requesterId: "u2",
    title: "Need laptop for remote work",
    description:
      "I work remotely and need a reliable laptop for video calls and document editing.",
    deviceType: "LAPTOP",
    preferredBrand: "Dell",
    isUrgent: false,
    countryCode: "NG",
    status: "ACTIVE",
    expiresAt: "2026-08-30",
    specId: "rs1",
  },
  {
    id: "r2",
    requesterId: "u4",
    title: "Tablet for my daughter's school",
    description: "My daughter needs a tablet for online classes and homework.",
    deviceType: "TABLET",
    preferredBrand: null,
    isUrgent: true,
    countryCode: "NG",
    status: "ACTIVE",
    expiresAt: "2026-07-20",
    specId: "rs2",
  },
  {
    id: "r3",
    requesterId: "u7",
    title: "Smartphone for business calls",
    description:
      "I need a working smartphone to manage my small business communications.",
    deviceType: "SMARTPHONE",
    preferredBrand: null,
    isUrgent: false,
    countryCode: "NG",
    status: "MATCHED",
    expiresAt: "2026-08-01",
    specId: "rs3",
  },
  {
    id: "r4",
    requesterId: "u10",
    title: "Laptop for graphic design coursework",
    description: "Enrolled in a design program and need a capable laptop.",
    deviceType: "LAPTOP",
    preferredBrand: "Apple",
    isUrgent: false,
    countryCode: "KE",
    status: "ACTIVE",
    expiresAt: "2026-09-01",
    specId: "rs4",
  },
  {
    id: "r5",
    requesterId: "u2",
    title: "Any working smartphone",
    description: "My phone broke and I need a replacement urgently.",
    deviceType: "SMARTPHONE",
    preferredBrand: null,
    isUrgent: true,
    countryCode: "NG",
    status: "ACTIVE",
    expiresAt: "2026-07-15",
    specId: "rs5",
  },
  {
    id: "r6",
    requesterId: "u4",
    title: "Laptop for coding bootcamp",
    description:
      "Starting a 6-month coding bootcamp and need a Linux-friendly machine.",
    deviceType: "LAPTOP",
    preferredBrand: "Lenovo",
    isUrgent: false,
    countryCode: "NG",
    status: "ACTIVE",
    expiresAt: "2026-08-10",
    specId: "rs6",
  },
  {
    id: "r7",
    requesterId: "u7",
    title: "Tablet for elderly parent",
    description:
      "Looking for a simple tablet my father can use for video calls.",
    deviceType: "TABLET",
    preferredBrand: "Apple",
    isUrgent: false,
    countryCode: "NG",
    status: "CLOSED",
    expiresAt: "2026-06-10",
    specId: "rs7",
  },
  {
    id: "r8",
    requesterId: "u10",
    title: "Laptop for university student",
    description:
      "Final year student needing a laptop for research and assignments.",
    deviceType: "LAPTOP",
    preferredBrand: null,
    isUrgent: false,
    countryCode: "KE",
    status: "ACTIVE",
    expiresAt: "2026-09-20",
    specId: "rs8",
  },
  {
    id: "r9",
    requesterId: "u2",
    title: "Smartphone for job hunting",
    description:
      "Need a phone to receive calls and access job listings online.",
    deviceType: "SMARTPHONE",
    preferredBrand: null,
    isUrgent: true,
    countryCode: "NG",
    status: "ACTIVE",
    expiresAt: "2026-07-25",
    specId: "rs9",
  },
  {
    id: "r10",
    requesterId: "u4",
    title: "Laptop for online classes",
    description:
      "Taking online courses and need a basic laptop to follow along.",
    deviceType: "LAPTOP",
    preferredBrand: null,
    isUrgent: false,
    countryCode: "NG",
    status: "ACTIVE",
    expiresAt: "2026-08-05",
    specId: "rs10",
  },
];
