export const users = [
  {
    id: "u1",
    firstName: "Amara",
    lastName: "Osei",
    email: "amara@example.com",
    role: "DONOR",
    country: "Ghana",
    countryCode: "GH",
    idVerified: true,
    idVerificationStatus: "VERIFIED",
  },
  {
    id: "u2",
    firstName: "Chidinma",
    lastName: "Eze",
    email: "chidi@example.com",
    role: "REQUESTER",
    country: "Nigeria",
    countryCode: "NG",
    idVerified: false,
    idVerificationStatus: "NONE",
  },
  {
    id: "u3",
    firstName: "Kwame",
    lastName: "Mensah",
    email: "kwame@example.com",
    role: "DONOR",
    country: "Ghana",
    countryCode: "GH",
    idVerified: true,
    idVerificationStatus: "VERIFIED",
  },
  {
    id: "u4",
    firstName: "Fatima",
    lastName: "Bello",
    email: "fatima@example.com",
    role: "REQUESTER",
    country: "Nigeria",
    countryCode: "NG",
    idVerified: false,
    idVerificationStatus: "PENDING",
  },
  {
    id: "u5",
    firstName: "Emeka",
    lastName: "Nwosu",
    email: "emeka@example.com",
    role: "BOTH",
    country: "Nigeria",
    countryCode: "NG",
    idVerified: true,
    idVerificationStatus: "VERIFIED",
  },
  {
    id: "u6",
    firstName: "Abena",
    lastName: "Asante",
    email: "abena@example.com",
    role: "DONOR",
    country: "Ghana",
    countryCode: "GH",
    idVerified: false,
    idVerificationStatus: "SUBMITTED",
  },
  {
    id: "u7",
    firstName: "Tunde",
    lastName: "Adeyemi",
    email: "tunde@example.com",
    role: "REQUESTER",
    country: "Nigeria",
    countryCode: "NG",
    idVerified: false,
    idVerificationStatus: "NONE",
  },
  {
    id: "u8",
    firstName: "Nkechi",
    lastName: "Okafor",
    email: "nkechi@example.com",
    role: "DONOR",
    country: "Nigeria",
    countryCode: "NG",
    idVerified: true,
    idVerificationStatus: "VERIFIED",
  },
  {
    id: "u9",
    firstName: "Kofi",
    lastName: "Agyeman",
    email: "kofi@example.com",
    role: "BOTH",
    country: "Ghana",
    countryCode: "GH",
    idVerified: true,
    idVerificationStatus: "VERIFIED",
  },
  {
    id: "u10",
    firstName: "Zainab",
    lastName: "Aliyu",
    email: "zainab@example.com",
    role: "REQUESTER",
    country: "Kenya",
    countryCode: "KE",
    idVerified: false,
    idVerificationStatus: "NONE",
  },
];
